---
name: learn-bosh
director_uuid: 4796378f-cc91-4d93-a1b0-75a9af101708

releases:
- name: learn-bosh
  version: latest

networks:
- name: default
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved: [10.244.0.<%= i*4 + 1 %>]
    static: [10.244.0.<%= i*4 + 2 %>]
    cloud_properties: {}
<% end %>

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 8
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 4

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties: {}
